version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: pg_video_stream
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: video_streaming
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
