spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/video_streaming
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 4GB
      max-request-size: 4GB

storage:
  upload-dir: ${user.dir}/uploads
